# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "node-#{i}" do |docker|
            docker.vm.box = "generic/ubuntu2004"
            docker.vm.hostname = "node-#{i}"
            docker.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 2
                libvirt.memory = 1024
                libvirt.default_prefix = "docker_"
                libvirt.nested = true
            end
            #docker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            docker.vm.provision "shell" do |s|
                ssh_pub_key = File.readlines("/home/juamsv/.ssh/id_rsa.pub").first.strip
                s.inline = <<-SHELL
                echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
                SHELL
            end
            docker.vm.provision :ansible do |ansible|
                ansible.playbook = "./provision/main.yaml"
            end
        end
    end
end

