# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "node-#{i}" do |docker|
            docker.vm.box = "generic/ubuntu2004"
            docker.vm.hostname = "node-#{i}"
            docker.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 1
                libvirt.memory = 1024
                libvirt.default_prefix = "swarm_"
                libvirt.nested = true
            end
            docker.vm.provision :ansible do |ansible|
                # ansible.playbook = "./provision/docker.yaml"
                ansible.playbook = "./provision/install_docker.yaml"
                ansible.playbook = "./provision/deploy-portainer.yaml"
                ansible.compatibility_mode = '2.0'
            end
            # docker.vm.provision "shell", path: "install_docker.sh"
        end
    end
end
