# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "node-#{i}" do |docker|
            docker.vm.box = "generic/ubuntu2004"
            docker.vm.hostname = "node-#{i}"
            docker.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 2
                libvirt.memory = 2048
                libvirt.default_prefix = "docker_"
                libvirt.nested = true
            end
            docker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
            docker.vm.provision :ansible do |ansible|
                ansible.playbook = "./provision/main.yaml"
            end
        end
    end
end

