# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

NODES = 1

Vagrant.configure("2") do |config|
    (1..NODES).each do |i|
        config.vm.define "node-#{i}" do |mezzanine|
            mezzanine.vm.box = "generic/ubuntu2204"
            mezzanine.vm.hostname = "node-#{i}.mezzanine.lab"
            mezzanine.vm.network "private_network", ip: "10.20.30.2#{i}"
            mezzanine.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 2
                libvirt.memory = 2048
                libvirt.default_prefix = "mezzanine_"
            end
            mezzanine.vm.provision :ansible do |ansible|
                ansible.playbook = "main.yml"
                ansible.tags = "pre_tasks"
                ansible.verbose = "vvv"
            end
        end
    end
end


