# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"        #VM Image used
    config.vm.hostname = "bitwarden-server"     #set the vm hostname            
    config.vm.synced_folder ".", "/vagrant_data", disabled: true
    config.vm.provider :libvirt do |libvirt|    #provider configuration, for libvirt/qemu things
        libvirt.cpus = 2                        # number of vCPUs
        libvirt.memory = 2048                   #ram memory
        libvirt.default_prefix = "bitwarden-teste"
        libvirt.nested = true
    end

    config.vm.provision "shell", path: "get-docker.sh"
    #Add of my pub ssh key to autorized keys inside VM.
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip #get your ssh pub key
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end
end
