# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

vms = {
    'debian' => {'memory' => '4096', 'cpus' => 4, 'ip' => '12', 'box' => 'debian/bullseye64'},
}

Vagrant.configure("2") do |config|
    vms.each do |name, conf|
        config.vm.define "#{name}" do |k|
            k.vm.box = "#{conf['box']}"
            k.vm.hostname = "#{name}"
            k.vm.synced_folder ".", "/vagrant_data", disabled: true
            k.vm.box_check_update = false
            k.vm.disk :disk, size: "50GB", primary: true
            k.vm.network :private_network,         
                :libvirt__network_name => "default",    
                :libvirt__always_destroy => false,
                :ip => "192.168.122.#{conf['ip']}"
            k.vm.provider :libvirt do |libvirt|    
                libvirt.cpus = conf['cpus']                       
                libvirt.memory = conf['memory']                   
                libvirt.default_prefix = "linuxadmin_"
                libvirt.nested = true
            end
            # k.vm.provision :ansible do |ansible|
            #     ansible.playbook = "./provision/playbook.yaml"
            #     # ansible.compatibility_mode = '2.0'
            #     ansible.verbose = "vvv"
            # end
            # Upload the public key pair
            k.vm.provision "shell" do |s|
                ssh_pub_key = File.readlines("/home/juamsv/.ssh/id_rsa.pub").first.strip
                s.inline = <<-SHELL
                echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
                SHELL
            end
        end
    end
end
