# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

NODES = 1

Vagrant.configure("2") do |config|
    (1..NODES).each do |i|
        config.vm.define "node-#{i}" do |ansible|
            ansible.vm.box = "generic/ubuntu2204"
            ansible.vm.hostname = "node-#{i}.ansible.lab"
            ansible.vm.network "private_network", ip: "10.20.30.4#{i}"
            ansible.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 2
                libvirt.memory = 2048
                libvirt.default_prefix = "ansible_"
            end
            ansible.vm.provision :ansible do |ansible|
                ansible.playbook = "main.yml"
                ansible.tags = "pre_tasks"
                ansible.verbose = "vvv"
            end
            # ansible.vm.provision "docker" do |d|
            #     d.run "nginx"
            # end
        end
    end
end


