# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

vms = {
    "master" => {'memory' => '2048', 'cpus' => 2, 'ip' => '10', 'box' => 'generic/ubuntu2004'},
    "node01" => {'memory' => '1024', 'cpus' => 2, 'ip' => '11', 'box' => 'generic/ubuntu2004'},
    "node02" => {'memory' => '1024', 'cpus' => 2, 'ip' => '12', 'box' => 'centos/8'},
    "registry" => {'memory' => '1024', 'cpus' =>2, 'ip' => '13', 'box' => 'generic/ubuntu2004'}
}

Vagrant.configure("2") do |config|
    vms.each do |name, conf|
        config.vm.define "#{name}" do |monitoring|
            monitoring.vm.box = "#{conf['box']}"
            monitoring.vm.hostname = "#{name}.monitoring.lab"
            monitoring.vm.synced_folder ".", "/vagrant_data", disabled: true
            monitoring.vm.box_check_update = false
            monitoring.vm.disk :disk, size: "50GB", primary: true
            monitoring.vm.network :private_network,         
                :libvirt__network_name => "monitoring",    
                :libvirt__always_destroy => false,
                :ip => "10.0.0.#{conf['ip']}"
            monitoring.vm.provider :libvirt do |libvirt|    
                libvirt.cpus = conf['cpus']                       
                libvirt.memory = conf['memory']                   
                libvirt.default_prefix = "monitoring_"
            end
            monitoring.vm.provision :ansible do |ansible|
                ansible.playbook = "./provision/main.yaml"
                ansible.verbose = "vvv"
            end
            # Upload the public key pair
            monitoring.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
            monitoring.vm.provision "shell", inline: "hostnamectl set-hostname #{name}.monitoring.lab"
        end
    end
end
