# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  (1..2).each do |i|                            #change the number for que nº of VMs you want. ex: (1..5)
    config.vm.define "node-#{i}" do |node|      #define the vm name 
      node.vm.box = "generic/ubuntu2004"        #VM Image used
      node.vm.hostname = "node-#{i}"            #set the vm hostname
      node.vm.network :private_network,         #create a new private network
        :libvirt__network_name => "default",    #select the libvirt network
        :libvirt__always_destroy => false       #for not exclude the network when execute vagrant destroy 
      node.vm.provider :libvirt do |libvirt|    #provider configuration, for libvirt/qemu things
        libvirt.cpus = 2                        # number of vCPUs
        libvirt.memory = 2048                   #ram memory
        libvirt.default_prefix = "k8s"
        libvirt.nested = true
      end

      #Add of my pub ssh key to autorized keys inside VM.
      config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip #get your ssh pub key
        # ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip #get your ssh pub key
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        #echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end

      # Vagrant.configure("2") do |config|  
      #   config.vm.provision "shell", path: "ks8_install.sh"
      # end

      #Update the system, install docker and enable run docker whitout root
      config.vm.provision "shell", inline: <<-SHELL

      SHELL
    end
  end
end
