# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "worker-node-#{i}" do |k8s|
      k8s.vm.box = "generic/ubuntu2204"
      k8s.vm.hostname = "worker-node-#{i}"
      k8s.vm.synced_folder ".", "/vagrant_data", disabled: true
      k8s.vm.network :private_network,         
        :libvirt__network_name => "k8s",    
        :libvirt__always_destroy => false,
        :ip => "10.0.0.2#{i}"
      k8s.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2084
        libvirt.default_prefix = "k8s_"
        libvirt.nested = true
      end
      k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
      # k8s.vm.provision :ansible do |ansible|
      #   ansible.playbook = "./provision/main.yaml"
      # end
    end
  end
  (1..1).each do |i|
    config.vm.define "master-node-#{i}" do |k8s|
      k8s.vm.box = "generic/ubuntu2204"
      k8s.vm.hostname = "master-node-#{i}"
      k8s.vm.synced_folder ".", "/vagrant_data", disabled: true
      k8s.vm.network :private_network,         
        :libvirt__network_name => "k8s",    
        :libvirt__always_destroy => false,
        :ip => "10.0.0.1#{i}"
      k8s.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 2084
        libvirt.default_prefix = "k8s_"
        libvirt.nested = true
      end
      k8s.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    end
  end

end
