# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

vms = {
    'ubuntu' => {'memory' => '512', 'cpus' => 1, 'ip' => '20', 'box' => 'generic/ubuntu2004'}
}

Vagrant.configure("2") do |config|
    vms.each do |name, conf|
        config.vm.define "#{name}" do |k|
            k.vm.box = "#{conf['box']}"
            k.vm.hostname = "#{name}"
            k.vm.synced_folder ".", "/vagrant_data", disabled: true
            k.vm.box_check_update = false
            k.vm.disk :disk, size: "50GB", primary: true
            k.vm.network :private_network,         
                :libvirt__network_name => "default",    
                :libvirt__always_destroy => false,
                :ip => "192.168.122.#{conf['ip']}"
            k.vm.provider :libvirt do |libvirt|    
                libvirt.cpus = conf['cpus']                       
                libvirt.memory = conf['memory']                   
                libvirt.default_prefix = "FreePBX"
                libvirt.nested = true
            end
            k.vm.provision :ansible do |ansible|
                ansible.playbook = "./provision/playbook.yaml"
                # ansible.compatibility_mode = '2.0'
                ansible.verbose = "vvv"
            end
            # Upload the public key pair
            k.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/id_rsa.pub"
        end
    end
end
