# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|    
    config.vm.define "rocky" do |rocky|
        rocky.vm.box = "centos/7"
        rocky.vm.hostname = "nfs-server"         
        rocky.vm.network :private_network,         #create a new private network
            :libvirt__network_name => "nfs",    #select the libvirt network
            :libvirt__always_destroy => true,
            :ip => "10.0.0.100"  
        rocky.vm.network :private_network,         
            :libvirt__network_name => "vagrant-libvirt",    
            :libvirt__always_destroy => false,
            :ip => "192.168.121.100"
        rocky.vm.provider :libvirt do |libvirt| 
            libvirt.cpus = 1                      # number of vCPUs
            libvirt.memory = 512                   #ram memory
            libvirt.default_prefix = "nfs_"
            libvirt.nested = true
        end
    end
    (1..1).each do |i|                            #change the number for que nº of VMs you want. ex: (1..5)
        config.vm.define "node-#{i}" do |node|      #define the vm name 
            node.vm.box = "generic/ubuntu2004"        #VM Image used
            node.vm.hostname = "node-#{i}"            #set the vm hostname
            node.vm.network :private_network,         
                :libvirt__network_name => "nfs",    
                :libvirt__always_destroy => true,       
                :ip => "10.0.0.10#{i}"
            node.vm.network :private_network,         
                :libvirt__network_name => "vagrant-libvirt",    
                :libvirt__always_destroy => false,       
                :ip => "192.168.121.1#{i}"
            node.vm.provider :libvirt do |libvirt|    #provider configuration, for libvirt/qemu things
                libvirt.cpus = 2                        # number of vCPUs
                libvirt.memory = 2048                   #ram memory
                libvirt.default_prefix = "swarm_"
                libvirt.nested = true
            end
            node.vm.provision "shell", path: "install_docker.sh"
        end
    end
end
