# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

vms = {
    'ubuntu' => {'memory' => '512', 'cpus' => 1, 'ip' => '11', 'box' => 'generic/ubuntu2004'},
    'debian' => {'memory' => '512', 'cpus' => 1, 'ip' => '12', 'box' => 'debian/bullseye64'},
    'rocky' => {'memory' => '512', 'cpus' => 1, 'ip' => '13', 'box' => 'rockylinux/8'}
}

Vagrant.configure("2") do |config|
    vms.each do |name, conf|
        config.vm.define "#{name}" do |k|
            k.vm.box = "#{conf['box']}"
            k.vm.hostname = "#{name}"
            k.vm.synced_folder ".", "/vagrant_data", disabled: true
            k.vm.network :private_network,         
                :libvirt__network_name => "default",    
                :libvirt__always_destroy => false,
                :ip => "192.168.122.#{conf['ip']}"
            k.vm.provider :libvirt do |libvirt|    
                libvirt.cpus = conf['cpus']                       
                libvirt.memory = conf['memory']                   
                libvirt.default_prefix = "ansible_lab_"
                libvirt.nested = true
            end
        end
    end
end
