# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "node-#{i}" do |ans|
            ans.vm.box = "generic/ubuntu2204"
            ans.vm.hostname = "node-#{i}.ansible.lab"
            ans.vm.synced_folder ".", "/vagrant_data", disabled: true
            ans.vm.network "private_network", ip: "10.20.30.1#{i}"
            # ans.vm.network :private_network,         
            #     :libvirt__network_name => "ansible",    
            #     :libvirt__always_destroy => false,
            #     :ip => "10.10.10.1#{i}"
            ans.vm.provider :libvirt do |libvirt|
                libvirt.cpus = 2
                libvirt.memory = 2048
                libvirt.default_prefix = "ansible_"
            end
            ans.vm.provision :ansible do |ansible|
                ansible.playbook = "./provision/host-file.yaml"
                ansible.verbose = "vvv"
            end
            ans.vm.provision "shell" do |s|
                ssh_pub_key = File.readlines("/home/juamsv/.ssh/id_rsa.pub").first.strip
                s.inline = <<-SHELL
                echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
                SHELL
            end
        end
    end
end


