# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.vm.box = "peru/windows-server-2022-standard-x64-eval"
    config.vm.hostname = "WS-22"
    config.vm.provider :libvirt do |libvirt|
        libvirt.default_prefix = "WS_22"
        libvirt.cpus = 4
        libvirt.memory = 4096
    end
end
