# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

vms = {
    'oracle8' => {'memory' => '4096', 
                'cpus' => 4, 
                'ip' => '11', 
                'box' => 'oraclelinux/8'}
}

Vagrant.configure("2") do |config|
    vms.each do |name, conf|
        config.vm.define "#{name}" do |k|
            k.vm.box = "#{conf['box']}"
            k.vm.hostname = "#{name}"
            k.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
            k.vm.box_check_update = false
            k.vm.disk :disk, size: "50GB", primary: true
            k.vm.provider :libvirt do |libvirt|    
                libvirt.cpus = conf['cpus']                       
                libvirt.memory = conf['memory']                   
                libvirt.nested = true
            end
            # k.vm.provision :ansible do |ansible|
            #     ansible.playbook = "./provision/playbook.yaml"
            #     ansible.verbose = "vvv"
            # end
            k.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
        end
    end
end
