# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|    
    (1..1).each do |i|                            #change the number for que nº of VMs you want. ex: (1..5)
        config.vm.define "node-#{i}" do |docker|      #define the vm name 
            docker.vm.box = "generic/ubuntu2004"        #VM Image used
            docker.vm.hostname = "node-#{i}"            #set the vm hostname            
            docker.vm.provider :libvirt do |libvirt|    #provider configuration, for libvirt/qemu things
                libvirt.cpus = 1                        # number of vCPUs
                libvirt.memory = 1024                   #ram memory
                libvirt.default_prefix = "swarm_"
                libvirt.nested = true
            end
            docker.vm.provision :ansible do |ansible|
                ansible.playbook = "./provision/docker.yaml"
                ansible.compatibility_mode = '2.0'
            end
            # docker.vm.provision "shell", path: "install_docker.sh"
        end
    end
end
