# -*- mode: ruby -*-
# vi: set ft=ruby :

# Settings for the Vagrantfile

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

cluster = {
  "master"    => {"memory" => "2048", "cpu" => "2", "ip" => "100", "image" => "generic/ubuntu2004"},
  "node-01"   => {"memory" => "1024", "cpu" => "2", "ip" => "110", "image" => "generic/ubuntu2004"},
  "node-02"   => {"memory" => "1024", "cpu" => "2", "ip" => "120", "image" => "generic/ubuntu2004"},
  "awx"       => {"memory" => "4094", "cpu" => "4", "ip" => "130", "image" => "generic/ubuntu2004"}
  # "registry" => {"memory" => "2048", "cpu" => "2", "ip" => "200", "image" => "generic/ubuntu1804"}
}

Vagrant.configure("2") do |config|

  cluster.each do |name, conf|
    config.vm.define "#{name}" do |cluster|
      cluster.vm.box = "#{conf["image"]}"
      cluster.vm.hostname = "#{name}.k8s.lab"
      cluster.vm.network :private_network,         
        :libvirt__network_name => "cluster_k8s",    
        :libvirt__always_destroy => false,
        :ip => "10.10.10.#{conf["ip"]}"
      cluster.vm.provider :libvirt do |libvirt|
        libvirt.default_prefix = ""
        libvirt.memory = conf["memory"]
        libvirt.cpus = conf["cpu"]
      end
      cluster.ssh.insert_key = false
      cluster.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    end
  end
end
