# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.vm.define "stack" do |stack|
        stack.vm.box = "generic/ubuntu2004"
        stack.vm.hostname = "devstack"
        stack.vm.provider :libvirt do |libvirt|
            libvirt.cpus = 2
            libvirt.memory = 4096
            libvirt.default_prefix = "dev"
        end
        # stack.vm.provision "shell", path: "install_stack.sh"
    end
end
